# Generated by Django 2.0.6 on 2018-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'available'), ('out_of_stock', 'out_of_stock'), ('removed', 'removed')], max_length=15)),
            ],
        ),
    ]
