# Generated by Django 2.0.6 on 2018-06-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_time',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
