# Generated by Django 2.0.6 on 2018-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20180610_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
