# Generated by Django 2.0.6 on 2018-06-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20180610_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exception_message',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
