# Generated by Django 2.0.6 on 2019-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_items',
            field=models.CharField(default=[], max_length=5000),
            preserve_default=False,
        ),
    ]
