# Generated by Django 2.0.6 on 2019-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_task_completed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
